services:
  - type: web
    name: dify-child
    env: docker          # Render に「Dockerfile を使う」と伝える
    plan: free           # 無料プラン
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false    # 最初は手動で起動確認
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: "5001"
